name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Automated.Testing.System/Automated.Testing.System.Web/

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    # Build
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -r linux-x64 -o cur
    # Test
    - name: Test
      run: dotnet test --no-build --verbosity normal
    # Deploy
    - run: rsync --rsh="sshpass -p ${{secrets.PASSWORD}} ssh -o StrictHostKeyChecking=no -l ${{secrets.USERNAME}}" --archive --compress --delete /home/runner/work/Automated-testing-system/Automated-testing-system/Automated.Testing.System/Automated.Testing.System.Web/cur/ ${{secrets.HOST}}:/srv/test/

