name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front/Automated.Testing.System/
    steps:
      - uses: actions/checkout@v2
      # Build
      - run: npm ci
      - run: npm run build
      # Deploy
      - run: rsync --rsh="sshpass -p ${{secrets.PASSWORD}} ssh -o StrictHostKeyChecking=no -l root" --archive --compress --delete dist/front 176.126.113.29:/var/www/
      #- run: rsync -e "ssh -p 22 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . @
